### ISSUE TITLE
How to run locally?

### ISSUE THREAD

**Issue by mherodev** [Yolk-HQ/next-routes#22]
Hey Yolk

I'm trying to crack how to run a local Next project against a local clone of `next-routes` so I can troubleshoot an error, but I'm having trouble linking the two projects.

My steps:

## Setup `next-routes`
1. Clone my own fork of this repo
2. `npm i`
3. `npm link`

## Setup my local Next.js project
1. Download and install https://github.com/zeit/next.js/tree/master/examples/with-next-routes
2. Rename `next-routes` to `@yolkai/next-routes` in routes and package.json
3. `npm i`
4. `npm link @yolkai/next-routes`

I've also tried by removing the `@yolkai/` in the fork, but I'm getting the same error either way:

```
mherold-mac:with-next-routes-app mherold$ npm run dev

> with-next-routes@1.0.0 dev /Users/mherold/git/temp/with-next-routes-app
> node server.js

module.js:549
    throw err;
    ^

Error: Cannot find module 'next-routes'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mherold/git/temp/with-next-routes-app/routes.js:1:82)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

I must be missing something obvious.

**Comment by mherodev** [comment]
Oh hey, it's because `main` points to `dist` and I haven't built the project... Let me try that, closing in a moment, I imagine... 🐨
